import asyncio
import json
import httpx
import os
from agentskg.agents.base import AgentConfig, BaseAgent
from agentskg.prompts.describe_prompt import DESCRIBE_ENTITY_PROMPT


class EntityDescriptionAgent(BaseAgent):
    def __init__(self, config: AgentConfig):
        self.config = config
        self.client = httpx.AsyncClient(timeout=120.0)

    async def execute(self, context: str, entity: str) -> str:
        """
        Asynchronously generate a one-sentence description for the entity.

        Args:
            context (str): The context information containing triples.
            entity (str): The target entity for which to generate the description.

        Returns:
            str: The description text generated by the model, or None if an error occurs.
        """
        api_url = os.getenv("API_URL")
        api_key = os.getenv("API_KEY")
        if not api_url or not api_key:
            print("Error: EntityDescriptionAgent failed to load API_URL or API_KEY.")
            return None

        api_url = f"{api_url.rstrip('/')}/chat/completions"
        user_content = (
            f"{DESCRIBE_ENTITY_PROMPT}\n"
            f"--- Input Triple ---\n{context}\n"
            f"--- Target ---\n{entity}"
        )
        payload = {
            "messages": [{"role": "user", "content": user_content}],
            "model": self.config.model_name,
            "max_tokens": self.config.max_tokens,
            "temperature": self.config.temperature,
        }
        headers = {
            "accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        }

        try:
            response = await self.client.post(api_url, json=payload, headers=headers)
            response.raise_for_status()
            response_data = response.json()

            if "choices" in response_data and response_data["choices"]:
                message = response_data["choices"][0].get("message", {})
                content = message.get("content")
                if content:
                    return content.strip()
                else:
                    print(
                        f"Error: 'content' missing in LLM response message: {message}"
                    )
                    return None
            else:
                print(
                    f"Error: 'choices' missing or empty in LLM response: {response_data}"
                )
                return None

        except httpx.HTTPStatusError as e:
            print(f"HTTP error occurred: {e.response.status_code} - {e.response.text}")
            return None
        except httpx.RequestError as e:
            print(f"Request error occurred: {e}")
            return None
        except json.JSONDecodeError as e:
            print(f"JSON decode error occurred: {e}. Response text: {response.text}")
            return None
        except Exception as e:
            print(f"An unexpected error occurred during LLM call: {e}")
            return None

    async def validate(self, result: str) -> bool:
        return isinstance(result, str) and bool(result)

    async def close(self):
        """Closes the underlying httpx client."""
        await self.client.aclose()
        print("EntityDescriptionAgent's HTTP client closed.")
